default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_api_development

test:
  <<: *default
  database: myapp_api_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>?database=myapp_api_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>?database=myapp_api_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>?database=myapp_api_production_cable
    migrations_paths: db/cable_migrate